version: "3.9"

services:
  api-server:
    build: .
    ports:
      - "8007:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: timescale/timescaledb:2.15.2-pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backup:
    image: alpine
    volumes:
      - .:/repo           # Your app code (where backup.sh lives)
      - ./backups:/backups     # Where backups are saved
      - timescale-data:/var/lib/postgresql/data  # Direct access to Postgres data volume
    entrypoint: ["/bin/sh", "-c", "while true; do /repo/backup.sh; sleep 86400; done"]

volumes:
  timescale-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/hslbussit/repo/dbdata